### ISSUE TITLE
Not getting the quality for improved cp vton as mentioned 

### ISSUE THREAD

**Issue by tryontester** [Yagami360/virtual-try-on_exercises_pytorch#3]
Really appreciate the amount of work you have done

I am currently only trying to derive inference using provided model and src code for improved cp vton.

I downloaded exact model as you mentioned and provided the images in your sample dataset as input but the results i got are very poor. Any reason why it should be the case. Did i miss any steps

I am using pytorch 1.4 and python 3.6. I only changed code in network.py to x = x.contiguous().view as it was giving me shape problem. Attaching images.

![0](https://user-images.githubusercontent.com/62136792/76611085-efdffb80-653f-11ea-9124-7de06a7e90a5.png)
![1](https://user-images.githubusercontent.com/62136792/76611088-f1112880-653f-11ea-9388-e4f4a920aa92.png)
![2](https://user-images.githubusercontent.com/62136792/76611091-f1a9bf00-653f-11ea-9458-08153e86e1cb.png)
![3](https://user-images.githubusercontent.com/62136792/76611095-f2425580-653f-11ea-83cb-5ec8bf04805b.png)
![4](https://user-images.githubusercontent.com/62136792/76611096-f2daec00-653f-11ea-93ab-95b5192911a1.png)

**Comment by Yagami360** [comment]
I changed bodyshape downsampling size 4 → 16 at this commit https://github.com/Yagami360/virtual-try-on_exercises_pytorch/commit/1625099a778dff0603d3ba5b74869bd3b039f982.
However, the downloaded checkpoints were learned at size 4 yet.

This problem may be solved by adding the following option to the inference script `test.py`.
`--poseA_bodyshape_downsampling_size 4`, `--poseB_bodyshape_downsampling_size 4`

**Comment by tryontester** [comment]
Yes this solved the problem. I went further and tried following combination

GMM checkpoint from improved cp vton with TOM checkpoint of my-vton (WUTON)  and it gives much realistic results. I think the TOM of my vton (wuton) requires to be trained for 200k for even better results. 

But you can try this to see if anything further can be done to improve as is.

**Comment by Yagami360** [comment]
> GMM checkpoint from improved cp vton with TOM checkpoint of my-vton (WUTON) and it gives much realistic results.

Yes, GMM in my-vton model aims to improve diversity of warped cloth input to TOM by using end2end network (GMM+TOM). 
By doing this, try-on images quatity from TOM was improved.

However, the quality of the warped cloth itself is better when using improved cp-vton GMM. So, In inference, the try-on image quality is higher using the improved cp-vton GMM and my-vton TOM.

> I think the TOM of myvton (wuton) requires to be trained for 200k for even better results.

Yes, I think so, too. But I haven't tried it because the training time of my-vton is very long and the cost of AWS instance bacome high.
